### ISSUE TITLE
等更新

### ISSUE THREAD

**Issue by Mrtao1028** [nebula-contrib/nebula-node#2]
可以发相关资料给我吗？
或许我可以协助 开发

**Comment by Mrtao1028** [comment]
找到了
https://github.com/vesoft-inc/nebula-clients/blob/master/node/How_to_update_interface.md

**Comment by laura-ding** [comment]
> 可以发相关资料给我吗？
> 或许我可以协助 开发

这个repo已经有基本的连接用，你要不要参与开发？设计文档我贴到这里。
