### ISSUE TITLE
v3.0.2 - Error: Cannot find module

### ISSUE THREAD

**Issue by imrefazekas** [nebula-contrib/nebula-node#24]
3.0.1 works fine, but 3.0.2 drops an error while importing ...
at line:
 ```const { createClient } = require( '@nebula-contrib/nebula-nodejs' )```

OS: MacOS 13.3.1
Node 20.1.0

```
Error: Cannot find module '/Users/vii/Ruse/Argus/argus-entitier/node_modules/@nebula-contrib/nebula-nodejs/index.js'. Please verify that the package.json has a valid "main" entry
```

**Comment by imrefazekas** [comment]
Was an NPM installation error...

**Comment by imrefazekas** [comment]
<img width="342" alt="Screenshot 2023-05-09 at 08 33 52" src="https://user-images.githubusercontent.com/975420/237013475-a6aa71f4-fe20-44e8-b5fc-4dc36f5af870.png">

NPM installs it and the "index.js" referenced by the package.json is not there ...

<img width="812" alt="Screenshot 2023-05-09 at 08 35 44" src="https://user-images.githubusercontent.com/975420/237013725-0cef0938-665f-4281-ac2e-eea17075cef1.png">

**Comment by imrefazekas** [comment]
<img width="280" alt="Screenshot 2023-05-09 at 08 36 50" src="https://user-images.githubusercontent.com/975420/237013928-67123807-65fb-4b67-b450-799e70d494d1.png">

3.0.1 still has it ...

**Comment by wey-gu** [comment]
Sorry, it seems I am not publishing it correctly, let me check.
