### ISSUE TITLE
What about TypeScript support?

### ISSUE THREAD

**Issue by visortelle** [nebula-contrib/nebula-node#4]
Hi!

Do you have any plans to evolve the node client?

Do you have any plans to rewrite it in TypeScript or at least add .d.ts type definitions?

Examples of the official drivers are written in TypeScript:
- Mongo - sources in TS, tests in JS.
  https://github.com/mongodb/node-mongodb-native
- Neo4j - mostly rewritten in TS.
  https://github.com/neo4j/neo4j-javascript-driver

**Comment by wey-gu** [comment]
Thank you @visortelle for bringing this :)! We are sorry that we had been lack of bandwidth evolving the node/JS client
Could we introduce TS to the nebula-node @nianiaJR @NicolaCage @hetao92?

**Comment by xigongdaEricyang** [comment]
We can consider add @types/nebula-node to support ts

**Comment by wey-gu** [comment]
Thanks @xigongdaEricyang

@nianiaJR @wujjpp , if I understand it correctly, now nebula-node is written in ts already, could we add @types/nebula-node now(or we had already done that)? Plz forgive me if it's a silly question(not familiar with node/typescript)

**Comment by wujjpp** [comment]
@wey-gu nebula-node was built on top of typescript, and ts declare files are included in build assets.

BTW don’t forget to publish build assets to NPM. Publishing steps are included in README.md

**Comment by wey-gu** [comment]
thanks @wujjpp ! As ts is supported(as nebula-node is ts-based itself), will close it.

also, i manually published it to `@nebula-contrib/nebula-nodejs` already, will create corresponding CI later.

ref: https://github.com/nebula-contrib/nebula-node/pull/10
