### ISSUE TITLE
contribute node.js client

### ISSUE THREAD

**Issue by Reid00** [nebula-contrib/nebula-node#5]
we do some second-dev on this project for Node client, it has been run for months in prod. we plan to donate it with new branch or other someway else you need, what process should us follow? this one https://docs.nebula-graph.com.cn/2.6.1/15.contribution/how-to-contribute/?

**Comment by wey-gu** [comment]
Amazing, @Reid00 thanks so much,

Could you please help put non-code design in an issue, and push code in PR?

It would be better that could be phased in several PRs while it's already squashed, you could put all changes in one PR.

Thanks!

**Comment by Reid00** [comment]
Got it, talked with my colleague, will do it later.

**Comment by wey-gu** [comment]
I wonder if it's possible to put the follow-up efforts as a nebula hackathon project?
@Reid00 @QingZ11

**Comment by Reid00** [comment]
talked with my colleague we think it's great.

**Comment by wey-gu** [comment]
> talked with my colleague we think it's great.

Saw your team 🤘🏻, 加油！

**Comment by wey-gu** [comment]
#6 was merged, thanks a ton to @wujjpp @Reid00 for the great work and @nianiaJR for the reviewing! 🎉
