### ISSUE TITLE
support of v3.0

### ISSUE THREAD

**Issue by wey-gu** [nebula-contrib/nebula-node#8]
as title

**Comment by wey-gu** [comment]
@wujjpp could you please help briefly guide me/the community on how it should be done to add v3 support? I/or others may spend some time generating needed thrift code and bringing it to nebula-node.

Thanks!

**Comment by wujjpp** [comment]
@wey-gu I didn't have v3 server for testing.

**Comment by wey-gu** [comment]
> @wey-gu I didn't have v3 server for testing.

If you don't mind, I could share a VM on the cloud with you(with nebula v3 installed), please reach me via mail(weyl.gu at gmail) or WeChat with id: :-D

```bash
echo c2l2dmVpCg== | base64 -d
```

**Comment by wujjpp** [comment]
@wey-gu required verification via wechat

**Comment by wujjpp** [comment]
@wey-gu required verification via wechat

**Comment by wujjpp** [comment]
@wey-gu please confirm the following defination:

1. https://github.com/vesoft-inc/nebula/blob/master/src/interface/graph.thrift#L83 
The type of `latency_in_us`, `i32` or `i64`. 
v2.x is `i32`, but v3.x changed to `i64` 

2. https://github.com/vesoft-inc/nebula/blob/master/src/interface/common.thrift#L110
v2.x is `string`, but v3.x is `binary`

3. https://github.com/vesoft-inc/nebula/blob/master/src/interface/common.thrift#L150
v2.x is `list<string>`, but v3.x is `list<binary>`

**Comment by wey-gu** [comment]
> 

for 1. it's intended as https://github.com/vesoft-inc/nebula/pull/2858 and https://github.com/vesoft-inc/nebula/issues/2650

for 2, and 3. it's binary since 2 years before, also in 2.0~5, in nebula-common it remains binary:
- https://github.com/vesoft-inc/nebula-common/blob/36f5ad9853ae63ddf96bfb21dd968e8ca66a8835/src/common/interface/common.thrift#L102
- https://github.com/vesoft-inc/nebula-common/blob/36f5ad9853ae63ddf96bfb21dd968e8ca66a8835/src/common/interface/common.thrift#L140

<img width="1207" alt="Screen Shot 2022-06-07 at 3 57 54 PM" src="https://user-images.githubusercontent.com/1651790/172327651-57c7a907-b7ca-439d-8478-8aa8ac7cb3e3.png">
<img width="1123" alt="Screen Shot 2022-06-07 at 3 58 09 PM" src="https://user-images.githubusercontent.com/1651790/172327664-5dd8a855-cb8a-4daa-af36-aeff6223a330.png">

Did i miss something here?

**Comment by wujjpp** [comment]
@wey-gu I'm not sure if all `string` type are convert to `binary`

**Comment by wey-gu** [comment]
> @wey-gu I'm not sure if all `string` type are convert to `binary`

I will verify this with other clients when I have some time later

**Comment by wujjpp** [comment]
@wey-gu I have test this PR in nebula v2.6.x and v3.1.0 , it seems working fine

**Comment by wey-gu** [comment]
> @wey-gu I have test this PR in nebula v2.6.x and v3.1.0 , it seems working fine

Wow, got it, 👍🏻

**Comment by wujjpp** [comment]
DONE
